bot.name=SpringSamuelichBot
bot.token=8061283864:AAE_5R58YvVAYVzVmVo6iGFp1dYvxV3Vnc4

spring.application.name=SpringBot

#indentifikator=ajeqcqtvq5va7o2i0bon
yandex.api.key=AQVN2xQgy2wLa-T60EBK0pw3-7qrrV__WmZKG36F
yandex.folder-id=b1gq7mkvmb11kvd0fkka
yandex.api.url=https://llm.api.cloud.yandex.net
yandex.model=yandexgpt


