###############################################################

bot.name=PUT_YOUR_BOT_NAME_HERE
bot.token=PUT_YOUR_BOT_TOKEN_HERE
yandex.api.key=PUT_YOUR_API_KEY_HERE
yandex.folder-id=PUT_YOUR_FOLDER_ID_HERE

###############################################################



spring.application.name=SpringBot

yandex.api.url=https://llm.api.cloud.yandex.net
yandex.model=yandexgpt
yandex.art.model=yandex-art/latest

yandex.temperature=0.9
yandex.max-tokens=2000

logging.level.com.telegrambot.SpringBot.yandexgpt.model.service=DEBUG